# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'ubuntu-18.04'

steps:

- script: terraform init
  workingDirectory: ./1-terraform
  displayName: 'SETUP: Run Terraform Init'

- script: terraform plan -auto-approve infra.tf 
  workingDirectory: ./1-terraform
  env:
    azure_subscription_id: "b8176ecc-784b-4f18-9639-882d1da3df67"
    azure_client_id: "761e7965-77e9-42e5-a2ad-c8f254330262"
    azure_client_secret: "fb97fc88-8d0d-46ae-a41f-24b27a9fcbd5"
    azure_tenant_id: "53d946b1-a3bd-45c9-a653-3afb6557e5c9"
    azure_location: "eastus"
  displayName: 'SETUP: Run Terraform Apply (target=file share)'