trigger:
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: ARM_AZURE_PRINCIPAL
- name: AZURE_LOCATION
  value: eastus 

steps:
- script: |
        az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
        az account set --subscription $(ARM_SUBSCRIPTION_ID)
    displayName: 'Login on Azure CLI'

- script: terraform init
    workingDirectory: ./1-terraform
    displayName: 'SETUP: Run Terraform Init'

- script: terraform apply -auto-approve
    workingDirectory: ./1-terraform
    env:
        azure_subscription_id:  $(ARM_SUBSCRIPTION_ID)
        azure_client_id:  $(ARM_CLIENT_ID)
        azure_client_secret: $(ARM_CLIENT_SECRET)
        azure_tenant_id:  $(ARM_TENANT_ID)
        azure_location: $(AZURE_LOCATION)
    displayName: 'SETUP: Run Terraform Apply (target=file share)'