# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
    - master
    
pool:
    vmImage: 'ubuntu-latest'

variables:
    - name: AZURE_LOCATION
      value: eastus 
    - group: ARM_AZURE_PRINCIPAL
    - group: TF_AZURE_REMOTE_BACKEND
    - name: VMAU
    - name: VMAP
    - name: FQDN

steps:

- script: |
    az login --service-principal --username $(ARM_CLIENT_ID) --password $(ARM_CLIENT_SECRET) --tenant $(ARM_TENANT_ID)
    az account set --subscription $(ARM_SUBSCRIPTION_ID)
  displayName: 'Login on Azure CLI'

- script: terraform init  -backend-config="storage_account_name=$(AZURE_STATE_STORAGE_NAME)" -backend-config="resource_group_name=$(AZURE_STATE_RESOURCE_GROUP_NAME)"
  workingDirectory: ./1-terraform
  displayName: 'INFRA SETUP: Run Terraform Init'

- script: terraform plan && terraform apply -auto-approve 
  workingDirectory: ./1-terraform
  env:
    TF_VAR_AZURE_LOCATION: $(AZURE_LOCATION)
  displayName: 'INFRA SETUP: Run Terraform PLAN and APPLY'

- script: |
    curUser=$(terraform output virtual_machine_admin_user)
    echo "##vso[task.setvariable variable=VMAU;]$curUser"
  workingDirectory: ./1-terraform
  displayName: 'SET: USER'

- script: |
    curPwd=$(terraform output virtual_machine_admin_pwd)
    echo "##vso[task.setvariable variable=VMAP;]$curPwd"
  workingDirectory: ./1-terraform
  displayName: 'SET: PWD'

- script: |
    curFqdn=$(terraform output domain_name_label)
    echo "##vso[task.setvariable variable=FQDN;]$curFqdn"
  workingDirectory: ./1-terraform
  displayName: 'SET: FQDN'

- script: sshpass -p $VMAP scp -o StrictHostKeyChecking=no usercreate.sh $VMAU@$FQDN:/home/$VMAU
  workingDirectory: ./2-sftpstart
  displayName: 'SETUP: Copy bash to remote server via SSH'

- script: sshpass -p $VMAP ssh $VMAU@$FQDN export UPASS=password123
  workingDirectory: ./2-sftpstart
  displayName: 'SETUP: Set new EV via SSH'

- script: sshpass -p $VMAP ssh -tt $VMAU@$FQDN 'sudo chmod 777 usercreate.sh'
  workingDirectory: ./2-sftpstart
  displayName: 'SETUP: CHMOD'

- script: sshpass -p $VMAP ssh -tt $VMAU@$FQDN 'sudo -S ./usercreate.sh'
  workingDirectory: ./2-sftpstart
  displayName: 'RUN: Run remote Script'
